// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: grpc_mensagens.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from grpc_mensagens.proto</summary>
public static partial class GrpcMensagensReflection {

  #region Descriptor
  /// <summary>File descriptor for grpc_mensagens.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GrpcMensagensReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRncnBjX21lbnNhZ2Vucy5wcm90byJVCgdNZXNzYWdlEhwKCmVudmlhZG9Q",
          "b3IYASABKAsyCC5Db250YWN0Eh0KC2VudmlhZG9QYXJhGAIgASgLMgguQ29u",
          "dGFjdBINCgV0ZXh0bxgDIAEoCSIyCgdDb250YWN0EgoKAmlwGAEgASgJEg0K",
          "BXBvcnRhGAIgASgJEgwKBG5vbWUYAyABKAkyMQoKTWVuc2FnZWlybxIjCgtT",
          "ZW5kTWVzc2FnZRIILk1lc3NhZ2UaCC5NZXNzYWdlIgBiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Message), global::Message.Parser, new[]{ "EnviadoPor", "EnviadoPara", "Texto" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Contact), global::Contact.Parser, new[]{ "Ip", "Porta", "Nome" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Message : pb::IMessage<Message> {
  private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Message> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GrpcMensagensReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Message() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Message(Message other) : this() {
    enviadoPor_ = other.enviadoPor_ != null ? other.enviadoPor_.Clone() : null;
    enviadoPara_ = other.enviadoPara_ != null ? other.enviadoPara_.Clone() : null;
    texto_ = other.texto_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Message Clone() {
    return new Message(this);
  }

  /// <summary>Field number for the "enviadoPor" field.</summary>
  public const int EnviadoPorFieldNumber = 1;
  private global::Contact enviadoPor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Contact EnviadoPor {
    get { return enviadoPor_; }
    set {
      enviadoPor_ = value;
    }
  }

  /// <summary>Field number for the "enviadoPara" field.</summary>
  public const int EnviadoParaFieldNumber = 2;
  private global::Contact enviadoPara_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Contact EnviadoPara {
    get { return enviadoPara_; }
    set {
      enviadoPara_ = value;
    }
  }

  /// <summary>Field number for the "texto" field.</summary>
  public const int TextoFieldNumber = 3;
  private string texto_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Texto {
    get { return texto_; }
    set {
      texto_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Message);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Message other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(EnviadoPor, other.EnviadoPor)) return false;
    if (!object.Equals(EnviadoPara, other.EnviadoPara)) return false;
    if (Texto != other.Texto) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (enviadoPor_ != null) hash ^= EnviadoPor.GetHashCode();
    if (enviadoPara_ != null) hash ^= EnviadoPara.GetHashCode();
    if (Texto.Length != 0) hash ^= Texto.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (enviadoPor_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(EnviadoPor);
    }
    if (enviadoPara_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(EnviadoPara);
    }
    if (Texto.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Texto);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (enviadoPor_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EnviadoPor);
    }
    if (enviadoPara_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EnviadoPara);
    }
    if (Texto.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Texto);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Message other) {
    if (other == null) {
      return;
    }
    if (other.enviadoPor_ != null) {
      if (enviadoPor_ == null) {
        EnviadoPor = new global::Contact();
      }
      EnviadoPor.MergeFrom(other.EnviadoPor);
    }
    if (other.enviadoPara_ != null) {
      if (enviadoPara_ == null) {
        EnviadoPara = new global::Contact();
      }
      EnviadoPara.MergeFrom(other.EnviadoPara);
    }
    if (other.Texto.Length != 0) {
      Texto = other.Texto;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (enviadoPor_ == null) {
            EnviadoPor = new global::Contact();
          }
          input.ReadMessage(EnviadoPor);
          break;
        }
        case 18: {
          if (enviadoPara_ == null) {
            EnviadoPara = new global::Contact();
          }
          input.ReadMessage(EnviadoPara);
          break;
        }
        case 26: {
          Texto = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class Contact : pb::IMessage<Contact> {
  private static readonly pb::MessageParser<Contact> _parser = new pb::MessageParser<Contact>(() => new Contact());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Contact> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GrpcMensagensReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Contact() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Contact(Contact other) : this() {
    ip_ = other.ip_;
    porta_ = other.porta_;
    nome_ = other.nome_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Contact Clone() {
    return new Contact(this);
  }

  /// <summary>Field number for the "ip" field.</summary>
  public const int IpFieldNumber = 1;
  private string ip_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ip {
    get { return ip_; }
    set {
      ip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "porta" field.</summary>
  public const int PortaFieldNumber = 2;
  private string porta_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Porta {
    get { return porta_; }
    set {
      porta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nome" field.</summary>
  public const int NomeFieldNumber = 3;
  private string nome_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Nome {
    get { return nome_; }
    set {
      nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Contact);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Contact other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Ip != other.Ip) return false;
    if (Porta != other.Porta) return false;
    if (Nome != other.Nome) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Ip.Length != 0) hash ^= Ip.GetHashCode();
    if (Porta.Length != 0) hash ^= Porta.GetHashCode();
    if (Nome.Length != 0) hash ^= Nome.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Ip.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Ip);
    }
    if (Porta.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Porta);
    }
    if (Nome.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Nome);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Ip.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ip);
    }
    if (Porta.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Porta);
    }
    if (Nome.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Contact other) {
    if (other == null) {
      return;
    }
    if (other.Ip.Length != 0) {
      Ip = other.Ip;
    }
    if (other.Porta.Length != 0) {
      Porta = other.Porta;
    }
    if (other.Nome.Length != 0) {
      Nome = other.Nome;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Ip = input.ReadString();
          break;
        }
        case 18: {
          Porta = input.ReadString();
          break;
        }
        case 26: {
          Nome = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
