// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: grpc_mensagens.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class Mensageiro
{
  static readonly string __ServiceName = "Mensageiro";

  static readonly grpc::Marshaller<global::Message> __Marshaller_Message = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Message.Parser.ParseFrom);

  static readonly grpc::Method<global::Message, global::Message> __Method_SendMessage = new grpc::Method<global::Message, global::Message>(
      grpc::MethodType.Unary,
      __ServiceName,
      "SendMessage",
      __Marshaller_Message,
      __Marshaller_Message);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::GrpcMensagensReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of Mensageiro</summary>
  [grpc::BindServiceMethod(typeof(Mensageiro), "BindService")]
  public abstract partial class MensageiroBase
  {
    public virtual global::System.Threading.Tasks.Task<global::Message> SendMessage(global::Message request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for Mensageiro</summary>
  public partial class MensageiroClient : grpc::ClientBase<MensageiroClient>
  {
    /// <summary>Creates a new client for Mensageiro</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public MensageiroClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for Mensageiro that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public MensageiroClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected MensageiroClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected MensageiroClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::Message SendMessage(global::Message request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return SendMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Message SendMessage(global::Message request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_SendMessage, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Message> SendMessageAsync(global::Message request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return SendMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Message> SendMessageAsync(global::Message request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_SendMessage, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override MensageiroClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new MensageiroClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(MensageiroBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_SendMessage, serviceImpl.SendMessage).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, MensageiroBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_SendMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Message, global::Message>(serviceImpl.SendMessage));
  }

}
#endregion
